### ISSUE TITLE
`datalad meta-aggregate` not working as anticipated

### ISSUE THREAD

**Issue by ddeepwel** [datalad/datalad-metalad#275]
I have created a very small data set containing just a single dicom file. When I run `datalad meta-aggregate`, I receive the following error message:

```
[ERROR  ] InsufficientArgumentsError(No valid metadata stores were specified for aggregation) (InsufficientArgumentsError) 
usage: datalad meta-aggregate [-h] [-d ROOT_DATASET] [--version] [PATH ...]
```

The help message makes it seem like no additional arguments are required, yet the error message say otherwise (InsufficientArgumentsError).

Relatedly, running `datalad meta-extract dicom image-000001.dcm` works perfectly fine.

I have the following version installed:
- datalad_metalad 0.4.2
- datalad-neuroimaging   0.3.1
- datalad 0.17.2

**Comment by christian-monch** [comment]
That is a bug in the parameter definition. Thanks for catching that. The usage-message should read:

```
usage: datalad meta-aggregate [-h] [-d ROOT_DATASET] [--version] PATH [PATH ...]
``` 

Will release a new update soon

**Comment by christian-monch** [comment]
Just released 0.4.4, which should fix the usage- and help-messages (no functional changes beyond that)

**Comment by ddeepwel** [comment]
The correct usage (`datalad meta-aggregate .`) still doesn't appear to work properly. I receive the following error:
```
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
[ERROR  ] not enough values to unpack (expected 2, got 0) (ValueError) 
```

I have also tried the absolute path to the dataset rather than `.` and receive the same error

**Comment by christian-monch** [comment]
Fixed by PR #280
